idioma/urls.py
from django.conf.urls import patterns, url

from idioma import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'), # ex: /idioma/
    url(r'^question/$', views.question, name='question'), # ex: /idioma/question
    url(r'^terminate/$', views.terminate, name='terminate'),
)

languages/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^idioma/', include('idioma.urls', namespace="idioma")),
)

idioma/models.py
#!/usr/bin/python
#-*- encoding:utf-8 *-*

from django.db import models


class Language(models.Model):
    label = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.label


class Topic(models.Model):
    label = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.label

    class Meta:
        ordering = ['label']


class ExpressionGen(models.Model):
    added_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)

    topics = models.ManyToManyField(Topic, related_name='topics')
    
    from_language = models.ForeignKey(Language, related_name='from_language')
    from_expr = models.CharField(max_length=255, help_text="Use | to separate multiple expressions")
    from_comment = models.TextField(max_length=255, null=True, blank=True)

    to_language = models.ForeignKey(Language, related_name='to_language')
    to_expr = models.CharField(max_length=255, help_text="Use | to separate multiple expressions")
    to_comment = models.TextField(max_length=255, null=True, blank=True)
    
    tatoeba_id = models.IntegerField(null=True, blank=True)

    def get_topics_labels(self):
        return [e['label'] for e in self.topics.values()]

    def __str__(self):
        return "%s [%s]" % (self.from_expr, self.to_expr)

    class Meta:
        verbose_name = 'Expression'
        unique_together = ("from_expr", "to_expr")

idioma/forms.py
#!/usr/bin/python
#-*- encoding:utf-8 *-*

from django import forms
from idioma.models import Language, Topic

languages = Language.objects.all()
no_topic = Topic()
no_topic.id = -1
no_topic.label = u'Everything'
topics = [no_topic]
topics.extend(list(Topic.objects.all()))

class InitPlayForm(forms.Form):
    question_language = forms.ChoiceField(label='Question language', choices=((l.id, l.label) for l in languages))
    response_language = forms.ChoiceField(label='Response language', choices=((l.id, l.label) for l in languages))
    topic = forms.ChoiceField(label='Topic', choices=((t.id, t.label) for t in topics))

    def clean(self):
        cleaned_data = super(InitPlayForm, self).clean()
        lang_from = cleaned_data['question_language']
        lang_to = cleaned_data['response_language']
        if lang_from == lang_to:
            raise forms.ValidationError("Question and response languages can't be identical")
        return cleaned_data


class QuestionForm(forms.Form):
    question = ""
    comment = ""
    current_question_nb = 0
    nb_of_points = 0
    nb_of_expr_left = 0
    score = ""
    result_message = ""
    result_message_style = ""
    previous_question = ""
    previous_answer = ""
    previous_user_answer = ""
    previous_answer_comment = ""
    user_answer = forms.CharField(initial="", widget=forms.TextInput(attrs={'autocomplete':'off'}))

idioma/views.py
#!/usr/bin/python
#-*- encoding:utf-8 *-*

from __future__ import division
import random

from django.shortcuts import render
from django.db.models import Q

from idioma.models import ExpressionGen, Language, Topic
from idioma.forms import InitPlayForm
from idioma.forms import QuestionForm


_expr_list = []
_cur_expr_index = 0
_wrong_answered_list = []

def index(request):
    """
    Main view
    """
    global _expr_list
    response_page = "idioma/index.html"
    page_title = "Idioma Home"
    if request.method == 'POST':
        init_play_form = InitPlayForm(request.POST)
        if init_play_form.is_valid():
            _wrong_answered_list = []
            question_lang_id = init_play_form.cleaned_data['question_language']
            response_lang_id = init_play_form.cleaned_data['response_language']
            topic_id = init_play_form.cleaned_data['topic']
            request.session['topic'] = u'Everything'
            if topic_id != '-1':
                request.session['topic'] = Topic.objects.get(id=topic_id).label
            
            _init_question_list(question_lang_id, response_lang_id, topic_id)

            request.session['question_language'] = Language.objects.get(id=question_lang_id).label
            request.session['response_language'] = Language.objects.get(id=response_lang_id).label

            
            request.session['current_question_nb'] = 1
            request.session['nb_of_points'] = 0
            form = QuestionForm()
            form.current_question_nb = request.session['current_question_nb']
            form.nb_of_points = 0
            _ask_question(form, request)
            response_page = "idioma/question.html"
        else:
            form = init_play_form
    else:
        form = InitPlayForm()
    request.session['plop'] = 'plop'
    return render(
        request,
        response_page,
        {
          'page_title': page_title,
          'form': form,
        }
    )

def terminate(request):
    page_title = "The end!"
    return render(
        request,
        'idioma/terminate.html',
        {
          'expr_list': _wrong_answered_list,
          'page_title': page_title,
        }
    )    

def question(request):
    """
    Ask / evaluate a question
    """
    page_title = "Question"
    form = QuestionForm(request.POST)
    if form.is_valid():
        _evaluate_answer(form.cleaned_data['user_answer'], form, request)
        form.previous_user_answer = form.cleaned_data['user_answer']
        if len(_expr_list) == 0:
            # No more questions in the list (=> only correct answers!) => start from the beginning
            return terminate(request)
    else:
        _evaluate_answer('', form, request)
        form.previous_user_answer = ''        

    form.previous_question = request.session['current_question']
    form.previous_answer = request.session['current_answer']
    form.previous_answer_comment = request.session['current_answer_comment']
    _ask_question(form, request)

    return render(
        request,
        'idioma/question.html',
        {
          'page_title': page_title,
          'form': form,
        }
    )

def _evaluate_answer(answer, form, request):
    """
    Evaluate the user answer
    @param answer : answer given by the user
    @param form : current form
    @param request : HTTP request
    """
    # An answer can have multiple items separated by ' | '. This means that all items are right
    right_answer_list = request.session['current_answer'].lower().split(' | ')
    if answer is not None and answer != '' and answer.lower() in right_answer_list:
        request.session['nb_of_points'] = request.session['nb_of_points'] + 1
        form.result_message = "Correct answer !"
        form.result_message_style = "isCorrectAnswer"
        del _expr_list[_cur_expr_index]
    else:
        form.result_message = "Wrong answer !"
        form.result_message_style = "isWrongAnswer"
        _wrong_answered_list.append(" | ".join(right_answer_list))

    score = round((request.session['nb_of_points'] * 20) / (request.session['current_question_nb']), 2)
    request.session['current_question_nb'] = request.session['current_question_nb'] + 1
    form.current_question_nb = request.session['current_question_nb']
    form.nb_of_points = request.session['nb_of_points']
    form.score = score # + " / 20"

def _ask_question(question_form, request):
    """
    Ask a question to the user
    @param question_form : a form reprensenting a question
    @param request : HTTP request
    """
    expr = _get_random_question()
    question_form.question = expr.to_expr
    question_form.comment = expr.to_comment
    question_form.nb_of_expr_left = len(_expr_list)
    request.session['current_question'] = question_form.question
    # Get answer
    request.session['current_answer'] = expr.from_expr
    request.session['current_answer_comment'] = expr.from_comment

def _get_random_question():
    """
    Choose a random question
    """
    global _cur_expr_index
    _cur_expr_index = random.randint(0, len(_expr_list) - 1)
    return _expr_list[_cur_expr_index]

def _init_question_list(question_lang_id, response_lang_id, c_topic_id):
    global _expr_list
    expr_gen_qs = ExpressionGen.objects.filter(
                        Q(from_language_id=response_lang_id, to_language_id=question_lang_id) |
                        Q(from_language_id=question_lang_id, to_language_id=response_lang_id)
                )
    if c_topic_id != '-1':
        expr_gen_qs = expr_gen_qs.filter(topics__id=c_topic_id)
    _expr_list = list(expr_gen_qs)

idioma/templates/idioma/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link rel="stylesheet" href="{% static 'idioma/style.css' %}"/>
    <script language="javascript">{% block script %}{% endblock %}</script>
    <title>{% block title %}Idioma{% endblock %}</title>
</head>

{% block bodystart %}<body>{% endblock %}
<div id="container">
    <div id="top">
        <center><h1>&raquo; {{ page_title }} &laquo;</h1></center>
    </div>

    <div id="leftBar">
    {% block leftBar %}
      <ul>
          <li><a href="{% url 'idioma:index' %}">Home</a></li>
          <li><a href="/admin/idioma">Django Admin</a></li>
      </ul>
    {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="bottom">
        <hr/><center>Copyright 2013 Idioma project - GNU/GPL v3 license</center>
    </div>
</div>
</body>
</html>

idioma/templates/idioma/index.html
{% extends "idioma/base.html" %}

{% block title %}{{ pageTitle }}{% endblock %}

{% block content %}
    <p>Welcome to Idioma!</p>
    <form name="initPlayForm" action="." method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <table>
      <tr>
          <td><input type="submit" value="Start" /></td>
      </tr>
    </table>
    </form>
{% endblock %}

idioma/templates/idioma/question.html
{% extends "idioma/base.html" %}

{% block title %}{{ pageTitle }}{% endblock %}

{% block script %}
    function autoSubmit(p_code) {
        if (p_code==13)
            submitData();
    }
{% endblock %}

{% block bodystart %}
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onload="document.forms[0].user_answer.focus()" onkeyup="javascript:autoSubmit(event.keyCode)">
{% endblock %}

{% block content %}
    <h1>Question {{ form.current_question_nb }} - Score : {{ form.nb_of_points }} ({{ form.score }} / 20)</h1>
    <h2>Nb of expressions : {{ form.nb_of_expr_left }}</h2>
    {% if form.previous_question %}
    <hr/>
        <div class="{{ form.result_message_style }}">{{ form.result_message }}</div>
        <div>The question was : {{ form.previous_question }}</div>
        <div>Your answer was : {{ form.previous_user_answer }}</div>
        <div class="correctAnswerResult">The correct answer was : {{ form.previous_answer }}</div>
        <div>The associated comment was : {{ form.previous_answer_comment }}</div>
    <hr/>
    {% endif %}
    <form name="questionForm" action="{% url 'idioma:question' %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td>Topic</td><td>{{ request.session.topic }}</td>
        </tr>
        <tr>
            <td>Question</td><td>{{ form.question }}</td>
        </tr>
        <tr>
            <td>Comment</td><td>{{ form.comment }}</td>
        </tr>
        <tr>
            <td>Translation</td><td><input autocomplete="off" type="text" name="user_answer" id="id_userAnswer" value=""/></td>
        </tr>
        <tr>
            <td><input type="submit" value="Answer" /></td>
            <td><input type="button" onClick="parent.location='{% url 'idioma:terminate' %}'" value="Terminate"></td>
        </tr>
    </table>
    </form>
{% endblock %}

idioma/templates/idioma/terminate.html
{% extends "idioma/base.html" %}

{% block title %}{{ pageTitle }}{% endblock %}

{% block bodystart %}
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
{% endblock %}

{% block content %}
    <h1>{{ pageTitle }}</h1>
    <h2>List of questions you've not answered correctly:</h2>
    <hr/>
    <ul>
    {% for expr in expr_list %}
        <li>{{ expr }}</li>
    {% endfor %}
    </ul>
{% endblock %}